baseURL = "/"
languageCode = "en-us"
theme = "terminal"
title = "callas1900.net"
pagination.pagerSize = 5
canonifyurls = true
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  google_analytics_id="G-EF8MECC9WY"
  RSSLink = "/index.xml"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[languages]
  [languages.en]
    [languages.en.params]
      title = "callas1900.net"
      subtitle = "A simple page of mine"
      keywords = ""
      copyright = "Copyright 2005-2024 callas1900.net All rights reserved."
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "callas1900"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "profile"
        name = "Profile"
        url = "/profile"
      [[languages.en.menu.main]]
        identifier = "quotes"
        name = "Quotes"
        url = "/quotes"

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]
