+++
title="Ollama, 余暇"
slug="ollama"
date="2025-01-02"
author=""
cover=""
tags=["随想"]
description="年末年始の休暇中にローカルLLMアプリケーションのOllamaを試してみた経験から、仕事における休息と余裕の大切さについて考察。Ollamaの使いやすさに驚きつつ、適切な休養が好奇心を満たす実行力を取り戻してくれることを実感。また、自己肯定感と休養の関係性について、コーチングの知見を交えながら思索を展開。休暇は単なるサボりではなく、新たな可能性を開く余裕を自分に与える重要な行為だという気づきを得る。"
showFullContent=false
draft=false
+++


Ollamaをインストールして触り始める。OllamaはLLMをローカルPCで動かすためのアプリケーションで、触ってみたら思ったより簡単にモデルを動かすことができて拍子抜けというか驚いた。体験やログの感じはDockerに酷似していて、バックグラウンドにDockerの技術が使われているか、思想として採用しているのかなと思う。

旧年はローカルLLMを、やろうやろうと思うだけ思って何もしてなかったけど、年末年始の休みが私に好奇心を満たすための正常な実行力を取り戻してくれた。やはり休みと余裕は大切なものだなと思う。

会社の趨勢を人質にして、自分に無理を強いるのは結果未来を潰すことになりかねないとふと思う。
「人は扱われるように、ふるまう」というのはコーチングのどこかで見た言葉だけど、案外これは自分自身のことにも当てはまると考えた。自己肯定感が高い状態は、よく自信が高い状態と同一視されるけども、元々Self-Affermativeは物事の成否の基準を世間一般（つまり他者）ではなく、自認している能力から評価することと私は聞いたし、考えている。
他者観察から磨かれる自認の精度と他者の評価を除外した自己評価は別物と考えることが大事だと思いついた。
結論を言うならば休みはサボりではなく、自分に他のことができる余裕を与える行為にもなると思うし、そのためには、自分が何かを成せることを信じてやる必要があると思います。

ついでにOllama+Open webuiのセットアップに関してのメモ

== Ollama+Open WebUI on WLS2

Ollama(アイコンかわいい):: https://ollama.com/
Open WebUI:: https://docs.openwebui.com/

環境: Windows11+WSL2

. OllamaのサイトからWSLにLinuxのインストール
.. `ollama` を叩いて応答があれば問題なし。
. Ollamaの確認として適当なモデルを走らせてみる。
.. Ollamaのサイトの右上あたりからModelsを探して、適当なモデル(llama3, mistral, gemma2あたり)を探して走らせてみる。
.. 各モデルの詳細のところに `ollama run llama3` のようなrunコマンドがあるのでそれをコピペして使う。
.. モデルによっては結構時間がかかる、走り始めたら適当な質問を入れてモデルが走っていることを確認。このまま使っても良いけど、UIがあったほうが添付ファイル等やりやすくなるので、UIをインストールする。
. `pip install open-webui` でインストール
. `open-webui serve` で開始
.. localhost:8080にアクセスして稼働確認、ここで左上のモデルにollamaでpullしてきたモデルが表示されていれば成功、通常自動で同期する。


'''
**注意: WLS側に全てインストールした理由**

最初はWindows側にOllamaを入れて、webuiをwsl側で入れてしまったが、そうするとOllamaのIPアドレスがローカルIP経由でないと見えなくなってしまったので、Windows側に２つともインストールするか、WSL側に寄せるかしないといけない。webuiのインストール要件にpythonのバージョン指定が細かめにあるので、asdfが使えるWLS側がやりやすいと考えたのでWLS側に寄せた。


