+++
title="創造プロセス - インプロファシリテーション講座の受講メモ"
slug="impro_facilitation_class"
date="2025-02-23"
author=""
cover="posts/2025/02/impro_facilitation_class/creative_process.png"
tags=["impro", "facilitation", "creative-process", '創造プロセス']
description="インプロファシリテーション講座を受けてのまとめ"
showFullContent=false
draft=false
+++

今回のテーマは場作り
ファシリテーション講座は「デザイン編」と「場作り編」に分かれているが、その日のゴール設計を以下にやるかのデザイン編と、実際にワークショップを駆動していく場作り編に分かれている。

考え方の根本にあるのはロバート・フリッツの創造プロセス

== 創造プロセス

使う考え方は凄くシンプルで、Realityを観察し、Visionを描き、Actionを決定する。

[cols="1,3a,3a"]
|===
|Reality
|
* 観察であり感想ではない
* Judgeなどの評価判断が少ないこと
* ちょっとした想像もOK
* Positiveな観察と、Negativeな観察のバランスをとる
|
Good:: 12時でお腹が空いてそう、体を動かしたいのかもしれない、頭を使うワークを一個前にやった
Bad:: やる気がない、運動不足
|Vision
|
* 言葉よりも情景や具体的な景色にしたほうが創造的になる
* ポジティブな言い方にするほうが、ファシリテーターが使いやすい
* ネガティブのポジティブ的な言い換えでもいい
* 小さいビジョン、凄いビジョンにしない
|
Good:: ゲーム後に、お互い感想を言い合っている
Bad:: 皆が大きな愛につつまれている状態
|Action
|
* ビジョンを達成するための行動
* 大事なことは正確なActionを見つけるよりも、決めて前に進むこと
* VisionとRealityの間のテンションを具体化したもの
|
Good:: よし、ワンワードをしよう
Bad:: （決められない）
|===

理解するために、創造プロセスの逆は問題解決プロセス。
課題問題を発見し、費用対効果を考え修正し、大枠の課題を修正する。
課題解決がうまくいかない場合は、対策を考えてブロッカーを取り除く。

対して、創造プロセスはActionの結果がVisionに届かないものだった場合は、新しいRealityがきたと捉え、またそこから新しいActionをVisionに向かって作っていく。

