+++
title="coaching, 年末思い出し"
slug="20250106"
date="2025-01-06"
author=""
cover=""
tags=["随想", "coaching"]
description=""
showFullContent=false
draft=false
+++

== LLMで行うコーチングと人が行うコーチングの違い
chatGPTに代表される大規模言語モデルを使ったセルフコーチングと、人が行うコーチングの差は何かと年末の飲み会の中で聞かれた件について、その時の回答を思い出しつつ書き留めておく。

どちらが有効か？どちらがコストパフォマンスが高いのかは一旦横に置いておいて、差分のみ。
そもそも私がやっているのはシステムコーチング®なので対集団コーチングなので違う点も置いておきます。

まず以下の２つの要素が大きく違うところだと私は認識してることから話しました。
「言外の情報」と「眉をひそめる返答」。

=== 言外の情報
言外の情報とは、LLMが苦手としているところでもあると考えてる箇所ですが、声色や身振り手振り身体接触などの情報です。私はコーチングの教育でそれらをチャネルと教育を受けました。オンラインとオンサイトだとそもそも情報のチャネル数が多くうまく使えばそもそもの有効な帯域が違うので、差が出たりもします。前アジャイルジャパンの時に話したLLM専攻している学生の方との話でも「そもそも文字化していないモン族の言葉などをLLMに落とし込むのは難しいよね」という話もしていました。コーチングの文脈に戻すと、コーチングではこれらの情報も使って伝えかえしを行ったりしていくので、これはLLMとの差の部分になります。

=== 眉をひそめる返答
昔、コーチの評価軸を書いたブログを見た時に、クライアントが眉をひそめる時間。という言葉を思い出しての発言でした。
また私のコーチングの師匠達の中には「コーチの仕事はどぶざらいをして、クライアントが目を背けてるものを見せてやることだよ」と言ってくれた人もいました。この話もしました。
これはLLMの教育過程（この言葉が正しいかはわからないけど）で、そういった眉をひそめる返答を評価する必要がありますが、結構難しいのではないかと考えてます。

=== イマココ
これを書いている時に、３つ目を思いつきました。
多分、LLMってイマココの概念を持っていないだろう。今この瞬間という感覚は恐らく持っていないはず。
過去のデータの評価とそこからの予測は出せるかもしれませんが、それが未来なのか、イマココから始まるものが何かという感覚は持っていないはずだし、不要なはずだ。確信は持てないが。
コーチングの実施において、詳しく書くのは面倒なので端折るがかなり重要なファクターです。

以上がLLMで行うコーチング（そもそもそれはコーチングなのか？）と、人が行うコーチングの差だという話をしました。

== ◯◯コーチとコーチングのコーチの違い
その話の流れで、こういった疑問も渡されました。
思い出しながら、もう少し具体化すると「特定分野におけるビジネス経験がなさそうな人が、その特定分野の人に対してコーチングしますといってるのはどうなのか？」といった内容です。詳細は間違えてるかもですが、そもそもその分野のことを教えることができない人にコーチができるのかと、野球経験ない人が野球コーチができるのか？といった疑問です。当然の疑問と思います。

そもそも、語源的にはチューターつまり家庭教師的な人のことをコーチといいはじめ、その後スポーツインストラクターもコーチというようになったので、◯◯コーチ。営業コーチ、アジャイルコーチなどが先にあり、そこからコーチが行う行動、つまり、教えること、一緒にやること、見守ることの中で、見守ることを特化させて、コーチング技法が生まれていきました。

なので２つのタイプのコーチに対しては、それぞれ違う期待値があります。
◯◯コーチの◯◯に技能が入る場合は、当然その技能に関する知識と経験あってのコーチです。
技能が入らないコーチの場合は、人の行動変容を促すことに特化したコーチです、別に特定分野の知識は必要ではありません。ただし、会話をスムーズにするためのドメイン知識があったほうが良いでしょう。

== 〆

それぞれ話しをしていて、コーチングってまだまだ認知されていない技術なのだなぁと思いました。
コーチングの世界にいると、コーチングの中身を知っているのが当たり前みたいに思ってしまうので、自戒が必要と考えました。
