+++
title = "インプロのシーンの作り方"
slug = "impro-scene-making"
date = 2025-04-04
author = ""
cover = ""
tags = ["impro"]
description = "海外インプロワークショップで学んだシーンの構成法。プラットフォーム、ティルト、終わりの3段階とIncidental Detailsなどの実践的なTIPSをまとめました。"
showFullContent = false
draft = false
+++

== 海外インプロワークショップに参加してきた
海外でワークショップに参加された方が、シェアワークショップをするとのこと、さらに経験者のみの高度な内容になるとのことだったので好奇心から内容をちゃんと確かめもせずに参加してきました。

参加してその海外のワークショップとは、 https://reactimpro.com/[REACT IMPRO] なる、キース・ジョンストンの高弟3名による10日間のドイツで開催されたインプロワークショップでした。 

その中で学びは沢山あったのですが、個人的にはシーンの作り方あたりが面白かったので、まとめておこうと思います。

== シーンの作り方
=== そもそもシーンとは？
インプロ（即興演劇）の細かい話はしないのですが、インプロを初心者の方が始めるとまずすぐに劇をやってみようとはならずに、どちらかというとインプロゲーム、シアターゲームといったものからスタートします。

対してシーンは、まさに一般的な即興演劇になります。
ではシーンをどのようにして作るのか？

=== シーンの構成

* プラットフォーム作り
* ティルト
* 終わり

プラットフォーム:: 日常パート、観客に対して二人の関係性を紹介する。突然即興なので、最低限の事以外は演者も知らない。「交番にいる警官二人で」とか「片方が椅子に座って、そこに歩いてくるところから」みたいな感じでインプロはスタートします。
ティルト:: Tilt、傾きという意味。プラットフォームで作られた二人の関係性が大きく変化します。
終わり:: ティルトの後、物語は終わりに向かって動いていきます。

=== TIPS
==== 全体的な話

相手をインスパイアする（これを本当にする）。相手はすごい。つまり、「あなたは速い、賢い」と関わるところから、さらに一歩進んで「あなたが仲間をインスパイアする方法が好き、観客を輝かせる方法が好き」と関わりをしていく。

ミスチバス（いたずらっこ）になる。

そして、ノーマルに舞台に上がったら何か変なことをするんじゃなくて、ノーマルに変であろうとしない、そしたら奇妙なことが起きる。

==== プラットフォームに関して

椅子でインスパイアする:: 椅子を並べるところから相手をインスパイアするところは始まっている。ただ椅子を置くだけじゃなくて演者をインスパイアする。

Incidental Details:: プラットフォームを作るときは、めちゃくちゃ詳細に多めの物事を決めることです。ついついプラットフォームを作ってる時は、ゆっくりスタートしたくなりますし、何かを決めていくのは怖い時もありますが、どんどん決めていく。自分たちが持ちきれない情報でも全然OKです。計算しない。

😐:::: 「そういえば、今日は一緒に集まったけど、うーん、コーヒーでも飲んでみる？」
🤩:::: 「そういえば、今日は一緒に映画でRRRを見るよね。渋谷のTOHOシネマズで14時からだけど、あと1時間あるけど新しくできたスターバックスの新作フラペチーノでも飲みに行かない？」

Positive Start:: 始める時は、ネガティブに始めない。お気に入りの曲を頭の中に流しながら入場する。


==== ティルトに関して
ティルトのキーは３つ

Block:: 相手からの提案や何かをなかったことにする。強く強くブロックしたほうがわかりやすくなる。 
Emotional Reaction:: まずリアクションする。突然笑ったり、突然泣いたり、突然怒ったり。理由はない、やりたくなったやつを突然やる。理由は後から正当化する。
Super Definition:: 予想されてたけど、予想されていなかったもの。一旦初心者は忘れていい。詳しくはCircle of Expectationの項目で。

==== 終わりに関して
ティルト後の主役は観客が決める。どちらの物語になっているかを感じ取って、その人が主役であるようにインプロのプレイヤーはシーンを終わらせていく。

練習方法:: 
* プレイヤーx2 / ディレクターx0-1 / 観客x1-3
* ティルト後、定期的にディレクターはシーンを止める、観客はプレイヤーどちらかを指差すか、それとも空、天井を指差す。指さされた方が主役になっているので、プレイヤーはその人をより主役にするようにやっていく。空、天井を指差された場合は、どちらが主役かはっきりしない状態のため、主役がわかるように動いていく。

== 感想、まとめ

他にも様々なTIPSがあるのですが、シーンづくりにフォーカスしておきます。インプロのシーンづくりはこうしなきゃいけない！というわけではないですが、一つの型とそれに合わせた練習方法が提示されたので、シーン作りで遊びやすくなった気がします。

