+++
title="パターン・ランゲージ読書ノート"
slug="pattern_language"
date="2025-02-15"
author=""
cover=""
tags=["読書ノート", "パターン・ランゲージ"]
description="パターン・ランゲージ読書ノート。途中まとめ"
showFullContent=false
draft=false
+++

== 課題感
https://www.keio-up.co.jp/np/isbn/9784766419870/[パターン・ランゲージ] をある程度読んだので読書ノートを書く。
この本を読んだ動機は、パターン・ランゲージをソフトウェア工学の世界で生きてきて、私自身があまりわかってないことを自覚していたので、そこに変化を与えたかった。

== よくネットで見るパターン記法

パターン・ランゲージを調べてみると以下のような形式を見る。

[NOTE]
====
. パターン番号
. パターン名
. 文脈（Context）
. 問題（Problem）
. フォース（Forces）
. 解決（Solution）
. 結果（Consequences）
. 関連パターン（Related Patterns）
. 具体例・実践のヒント（Examples/Implementation）
====

人が作ったものを読む分には良いけど、書き始めるためには慣れていないと書きにくいなと感じていた。
もう少しいうと、数パターン書いて終わる。私には書き上げるための根気が足りてないのだと判断していた。

= パターン・ランゲージを読んで

パターン・ランゲージは応急処置的な社会から創造的な社会へ変えるために使用していく。
では、パターン・ランゲージの応急処置的な世界での姿はどうなるのか考えて見ると、模範解答集と捉えました。

[%header, cols="1,1"]
|===
|パターン・ランゲージ
|模範解答集

|創造的な社会
|応急処置的な社会

|What/Why/How を書き、When/Where/Whoは書かないことで抽象的でどこでも使えるものにする
|抽象化よりも具体的で即時対応できる方法を書く

|組み合わせ、重なり合いを持たせながら、１つの「全体」を構成する
|モレなく、ダブりなくを目指す
|===

== パターンとパターン・ランゲージ

これは、「解答」と「解答集」の関係と似ている。
ただし、パターン集とならないのは、なぜか？

パターン:: 創造を支援するための抽象的な解決方法。一定のフォーマットに従って書かれる。
パターン集:: パターンが複数集まっているもの
パターン・ランゲージ:: 有限のパターンの重ね合わせや関係性も表現され、無名の質を実現するために使われるもの。


== 一番簡単なパターンの形

[cols="1,2,1"]
|===
|パターン名
|パターンの名前
|
|状況（Context）
|ある問題が生じる状況
|Why
|問題（Problem）
|生じている問題の内容
|Why
|解決（Solution）
|問題の解決方法
|What, How
|===

== 次に足していくもの

フォース（Force）:: 問題を作っている力の対立・葛藤

これが足された時に、

解決（Solution）:: 力の対立・葛藤を解消する解決方法

ここまで書くと以下も書いた方が良いかもしれない。

結果（Consequence）:: 期待される結果

== 残りを考える
最初に書いた一般的なパターンの例を今どこまでサポートしているかというと、

**パターン番号** +
+++<s>パターン名</s>+++ +
+++<s>文脈（Context）</s>+++ +
+++<s>問題（Problem）</s>+++ +
+++<s>フォース（Forces）</s>+++ +
+++<s>解決（Solution）</s>+++ +
+++<s>結果（Consequences）</s>+++ +
**関連パターン（Related Patterns）** +
**具体例・実践のヒント（Examples/Implementation）** +

残りの項目に関しては、パターンを上げていき、それらがランゲージ化していく過程で必要になっていく**パターン番号**と**関連パターン**そして、実践者にヒントになるものを書き足していくことになる。

ここで少し安心できたのは、とりあえずまずは一番簡単な要素からパターンはスタートして良いとの気付きだった。

== パターンの使用方法
パターンは創造的活動に使われいないと、ただのメモ書きになってしまう。以下の用法で使われることでブラッシュアップされることを期待している。

* 認識のメガネ
* 思考の構成要素
* コミニケーションの語彙
