+++
title="20241231"
slug="20241231"
date="2024-12-31"
author=""
cover=""
tags=["大晦日"]
description="大晦日の振り返り"
showFullContent=false
draft=false
+++

== 書き物 
=== Blog
もう全然書いていないことを許容してしまっていたが、もしかしたら執筆的な仕事を頂く可能性があるかもしれないので、書かなきゃなぁと思っていたところに、「好き」を言語化する技術で「自分だけの文章」を書く必要性が説かれていたので、書く気持ちだけは高まっているが、毎年この時期は高まっている気もする。

=== コーチングアジャイルチームス
ついに長らく続いてた本は刊行された。嬉しいし肩の荷が降りたがマニアックに受けてる気がしている。一般受けしたいなと思う。

== 体作り
=== Running
ゆっくり回復していこうとしていたが、結局全然やらない自分を変えてもらうために3月に新しいガーミンウオッチを買ったところ、そこに内蔵されていたガーミンコーチ機能で結構走った。途中体調不良が挟まってそこは大人しくしていた。12月は特に２回風邪を引いて、２回副鼻腔炎になったので、本当にあまり走れていないがそんなものかな、来年３月のハーフマラソンを目指して頑張っていきます。

=== Cycling
完全停止中ではあるが、テールランプを買ったので少しあたたかくなったら、乗り始めようかなー。一つの交通手段として使いたい。

== お仕事
大きく来年は変動がくるのか、何も変わらないのか。
=== Coding
年始はコーディングしてたけど、残り半年は全然書けてない。少し落ち着いて何か書きたいな。

=== Coaching
今年はアジャイルコーチングとシステムコーチングがまじり始めた面白い年だった

=== 演劇系
人生ではじめて、演劇をして料金を頂くという経験をさせて頂いた。応用演劇含め学べることは、いっぱいあるので楽しんでいきたいな。来年は舞台にも立ってみたいと思います。

== Otaku
=== アニメ・漫画
リゼロ３期はかなり良い作品。他のアニメはあまり見れてない。漫画は見よう見よう思ってる宝石の国をアニメの影響で読み始めそう。
=== Game
モンスターハンターワイルズに向けて、ワールドクリアからのアイスボーンを楽しくやれていた。またついにxboxコントローラーを導入したことで、ETS2も再開。

== 〆
良く生き、良く楽しみ、新しいことをし、今までのことも楽しめた。2025年も古きを楽しみ新しきを探せるようでありたい。
