+++
title="フォーラムシアター専科基礎認定コース"
slug="theatre of the oppressed"
date="2024-02-13"
author=""
cover=""
tags=["Forum Theatre"]
keywords=["Forum Theatre"]
description=""
showFullContent=false
draft=true
toc=true
+++

:sectnums:
:toc:

== フォーラムシアターとは？
今回、講師としてせつさん（花崎攝）が行ったアプライドシアター研究所主催のフォーラムシアター・プラクティショナーの専科基礎認定コースを３日間受講してきました。
耳慣れない言葉が並んでる気もするので、まずは用語を簡単に解説します。

アプライドシアター:: 応用演劇のこと。演劇の技術、演劇の手法を応用的に使って社会のために働きかけのこと。
フォーラムシアター:: 討論演劇。アウグスト・ボアール(Augusto Boal、以下Boal）が作成した、演劇の知恵を使って社会改革をする手法。被抑圧者の演劇という絶版書で有名になった。弁証法的なアプローチを軸に構造主義的な考え方も持っている。

イメージシアターシリーズ:: Boalが作った彫像劇に代表される。表現することと見ることが隣接している演劇のこと。

GAMES FOR ACTORS AND NON-ACTORS:: Boalが集めたシアターゲーム集の本。ゲームとは何かは後述します。Adrian Jacksonが英語に翻訳。せつさんは主にAdrian Jacksonの師事を受けたとのこと。

== タブロー・彫像・イメージシアターを学ぶ
* 自分で表現
* 相手を使って表現
* 何かを表現
* 何かの構成要素を表現

一つの音と一つの動き

マシン

== フォーラムシアターの構造

1. エクササイズ(体を知る)
2. ゲーム（ダイアローグ的）
3. アンチ・モデルの生成
4. フォーラムを開く
5. フォーラムを閉じる

=== エクササイズとゲーム

この２つに明確な違いはないとしながら、ボアールは分けているようです。
教えて頂いた中では、エクササイズは体を知る、つまり筋肉を知ることが主目的でありモノローグ的になる。ゲームはダイアローグ的であり、関係性を知ることを目的にしている。

力関係の上下が抑圧を生成する。

* コロンビアの催眠術師
* ミラーゲーム
* 手を繋いだミラーゲーム
* 彫像
* 彫像を使った
* 一つの動きと一つの音 
* マシン

=== アンチ・モデル
アンチモデルの長さは10分ほど
主人公にとって良くない結末で終わる演劇。出来なかった物語。

=== アンチ・モデルの製造方法


==== ブラッシュアップ方法
**Cops in The Head** や **Rainbow of desire** などを使って体験をより理解する。 +
Cops... は抑圧状況の役割を彫像劇でクリアにしていく +
Rainbow... は同じ彫像劇だが心的、感情的なものをコンステレーションでクリアにしていく


=== フォーラムを開く
ショーカー
マジカルな解決方法に目を光らせる人

「現実と離れすぎるとカタルシスだけになる」

スペクトアクター
* 体験を話す
* 参加して代わりに演じる
* 知恵を出す


== フォーラムシアターはどこで使うのか？
ワークショップ形式、ショー形式どちらもあり

== せつさんの話より

ボアールの変遷、南アメリカからヨーロッパに移って


