+++
title="フォーラムシアター専科基礎認定コース"
slug="theatre of the oppressed"
date="2024-02-13"
author=""
cover="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Augusto_Boal_nyc5.jpg/1280px-Augusto_Boal_nyc5.jpg"
tags=["演劇教育", "応用演劇", "Forum Theatre"]
keywords=["Forum Theatre"]
description="今回、講師としてせつさん（花崎攝先生）が行ったアプライドシアター研究所主催のフォーラムシアター・プラクティショナーの専科基礎認定コースを３日間受講してきました。備忘録としてまとめます。"
showFullContent=false
draft=false
toc=true
+++

:sectnums:
:toc:
:toclevels: 1

== フォーラムシアターとは？
今回、講師としてせつさん（花崎攝先生）が行ったアプライドシアター研究所主催のフォーラムシアター・プラクティショナーの専科基礎認定コースを３日間受講してきました。

== 用語解説
耳慣れない言葉が並んでる気もするので、まずは用語を簡単に解説します。

アプライドシアター:: 応用演劇のこと。演劇の技術、演劇の手法を応用的に使って社会のために働きかけること。
フォーラムシアター:: 討論演劇。アウグスト・ボアール(Augusto Boal、以下Boal）が作成した、演劇の知恵を使って社会改革をする手法。主著「被抑圧者の演劇」で有名に。日本語版は現在絶版。弁証法的なアプローチを軸にしている。

イメージシアターシリーズ:: Boalが作った彫像劇に代表される。表現することと見ることが隣接している演劇のこと。

GAMES FOR ACTORS AND NON-ACTORS:: Boalが集めたシアターゲーム集の本。ゲームとは何かは後述します。Adrian Jackson が英語に翻訳。せつさんは主にAdrian Jacksonの師事を受けたとのこと。

=== エクササイズとゲーム

この２つに明確な違いはないとしながら、ボアールは分けているようです。
教えて頂いた中では、

エクササイズ:: 体を知る、つまり筋肉を知ることが主目的でありモノローグ的になる。
ゲーム:: ダイアローグ的であり、関係性を知ることを目的にしている。


* コロンビアの催眠術師
* ミラーゲーム
* 手を繋いだミラーゲーム
* 彫像
* 彫像を使った
* 一つの動きと一つの音 
* マシン

TIP: 力関係の上下が抑圧を生成する。

== タブロー・彫像・イメージシアターを学ぶ


彫像演劇での表現は、アンチモデル制作時の核（ドラマトゥルギー）になると私は捉えています。

彫像演劇は表現の幅を小さくすることでそこに何が起きているのかをわかりやすくするものとして私は受け取っています。

=== 自分を彫像にする
まずは一番単純なものは「彫像」です。
これは何かを表現するために自分の体を彫刻作品として、何かを表現するただそれだけです。

=== 相手を彫像にする
次に、この彫刻を自分の体ではなく、相手の体を使ってやっていきます。十分に相手の信頼関係があるのであれば、触って動かしていくのが一番わかりやすのですが、昨今では危ない場合もあるので、十分に安全でない場合は、口頭での指示や、ジェスチャーで指示することも必要です。

=== 集団彫刻作品
次に集団で何かを表現していきます。例えば朝の家族の様子を集団の彫像で表現してみましょう。

=== 抽象度を上げていく
最後に、集団でなにかの構成要素を表現することにチャレンジします。私達が練習としてやったのはアイドルの構成要素をアイドル自体を表現せずに、真ん中に"アイドル"がいるものとしておいた椅子を中心にアイドルをアイドルとして成り立たせている社会装置をそれぞれ表現しました。

=== 彫像自体のアップグレード、
彫像自体は動かないで、ストップした動きで何かを表現する試みですが、これだけだと舞台作品として表現力の幅が難しい時もあるので、そこに**"一つの音と動き"**を追加します。

繰り返し可能な動きと、それに付随する自由な音、繰り返し可能な台詞でも擬音や擬態語などでも問題ありません。これを追加することでわかりやすさがぐっと上がります。

=== マシンのエクササイズ
一つの音と動きを連動させていくゲームです。無人化された工場では様々な機会が連動して何かを製造しています。ゲームとして、誰かが一つの音と動きで何かを制作したら、即興的に次々と繋げていきましょう。我々の社会もこうやって物事が動いているとも捉えれます。

=== ここでのまとめ
ここでは２つの表現方法を学びます。

一つはまったく動かないけど全身で表現をしている「彫像」これは、自分-> 相手 -> 集団で何かを表現 -> 集団で何かの構成要素を表現と広げていきます。

また彫像自体も変化可能で、「一つの音と動き」にすることで、表現の幅を広げることができます。これも彫像と同じ自分から集団への展開ができます。

さらに、バラバラに状態を表現することから、連動して表現することをマシンから学習します。

CAUTION: これは、学んだものを私が解釈しているだけなので間違えてる箇所があると思います。

== フォーラムシアターの構造
さて肝心のフォーラムシアターですが、以下のような構造になっています。

. エクササイズ(体を知る)
. ゲーム（関係性を知る）
. アンチ・モデルの生成
. フォーラムを開く
. フォーラムを閉じる

実際には、アンチ・モデルの生成までと、実際にフォーラムを開くまでの間には時間があります。その間に役者は稽古をしたりアンチ・モデルのブラッシュアップをします。

ではアンチ・モデルの生成の仕方に入っていきます。

== アンチ・モデルを生成する
アンチモデルの長さは10分ほど、主人公（被抑圧者）にとって良くない結末で終わる演劇。出来なかった物語。

=== アンチ・モデルのドラフトを作る
まず最初は、被抑圧者に「一つの動きと音」の彫像劇で抑圧されたシーンを説明してもらいます。被抑圧者は喋って説明せず、最低限の彫像役に対する一つの音のリクエストの時のみ発話します。

出来上がった、彫像劇を観客席から見てもらって、違和感があれば直してもらっても良いでしょう。

=== 役作り
各配役に肉付けしていきます。ここで大事なのは相手のことを被抑圧者も詳しく知らないこともあって当然です。リアリティに軸足を置くことが基本ですが、わからないところは構造をサポートするために創造していきます。名前、年収、服装、性別、雰囲気などなど詰めていきます。それぞれの役のイデオロギー、心情も決めていきます。

=== ドラフトの上演
出来上がったドラフト版のアンチ・モデルを上演しましょう。
観客役から、意見を色々拾い上げてブラッシュアップの元ネタにします。

=== ブラッシュアップ
ブラッシュアップが目指す方向は、フォーラムシアターつまり討論演劇としてより良くなる。良い回答よりも良い議論が起こるように目指していきます。

主な調整軸は「演劇性」と「反省的思考」。演劇性とは虚構性とも言える、実際の場面では起こらないこと、主人公をより主人公に見えるような舞台配置やモノローグの挿入、スポットライトなどなどのことです。

演劇性が上がることで、生々しさが緩和され、抽象化され、観客が自分ごととして考える余地が生まれてきます。ただし、これをやり過ぎると単なる劇が生まれるだけになり、感動は起きるかもしれませんが、誰も立ち上がって舞台に上がろうとしなくなります。

    「現実と離れすぎるとカタルシスだけになる。」

とはせつさんの言葉です。

逆に反省的思考が強すぎると、リアル過ぎて事件のドキュメンタリーになってしまい。これも観客は中に入ってこようとしません。他人の物語になり同情的になることはあっても、それを変えることに躊躇が生まれるかもしれません。

これらは、テーマ、観客の層などなど考慮して調整していく必要があります。一つの目安として面白い話を聞いたのは、観客がスペクトアクターになってない場合は、椅子の背もたれにしっかり体を預け、鑑賞モードになっているという話を聞きました。

==== 被抑圧者の被抑圧時の状況をより理解するためのゲーム
さらに全ての被抑圧者がトレーニングを受けたからといって、彫像劇で完全に自分の考えていることを表すことが出来るとは限りません。

**Cops in The Head（頭の中の警官）** や **Rainbow of desire（欲望の虹）** などを使って被抑圧者の体験をより理解することも必要であれば行って下さい。

Cops in The Head:: 抑圧状況の自分の中の内的役割を彫像劇でクリアにしていく 
Rainbow of desire:: 同じ彫像劇だが心的、感情的なものをコンステレーション（布置）的にクリアにしていく。

== フォーラムを開く
さぁいよいよフォーラムを開きます。

フォーラムを開く時にはジョーカーと呼ばれる進行役が全体の進行指揮をとります。
全体の進行は以下のようになります。

=== 全体の進行
. ジョーカーが10-15分、「被抑圧者の演劇」の趣旨説明を行う
. ゲームのルールの説明
. いくつかのエクササイズを行う（文化、国、地域、実施時期などによって異なる）
. 彫像演劇。スペクトアクターは彫像の表現するテーマについて意見を出し合う。
. アンチ・モデルの提示。それをスタートにフォーラムに入る。

=== アンチモデル上演時にそれぞれの役割に期待されている行動
ジョーカー::
* マジカルな解決方法に目を光らせる

スペクトアクター::
* 体験を話す
* 参加して代わりに演じる
* 知恵を出す

アンチ・モデルのアクター::
* 弁証法的である、つまりアンチ・モデルを解決しようとする力に対して簡単に抑圧が打ち破れないことを示す。
* 十分に有効であると役として感じた時は、解決に動いても良い

=== アンチ・モデルの進行
まずは、一度アンチ・モデルの上演を最初から最後までスペクトアクターに見てもらいます。二度目の上演、スペクトアクターは好きなタイミングで「ストップ」をかけることが出来ます。基本的にはまず被抑圧者その人に代わって舞台に立つところから始めます。もし綺麗に解決出来たとしてもマジカルな解決であれば、ジョーカーはNOと言っても良いです。もう一度目的を言いますが、良い解決ではなく良い議論が起きることが目的です。

=== いつ終わるのか？
議論は終わることが無いのが普通です。時間と共に終わらせていきましょう。この後どうするかはトレーニングの中では語られていませんでした。ORSCer としては、この終わり方はディープデモクラシープロセスが終わった時と似ているので、各人のケアと共に場が学習したものをELAの手順で回収できればと考えました。

=== これで何が得られるのか？
当然解決方法は得られません。アンチ・モデルの元ネタを提供してくれた被抑圧者も直接的に救済されるわけではありません。フォーラムを通じて参加者の教育が行われます。そういった形の社会変革です。

== フォーラムシアターはどこで使うのか？
どこで使えるのかは、基礎トレーニングを受けた私もわかっていません。使えるといえばどこでも使える気がします。会社全体の教育を勧めたいパワハラ・セクハラ問題などがぱっと思いつくところですが、まだまだ可能性はあると思います。

一応「使えない」ケースも紹介しておきます。フォーラムシアターはあらゆる「抑圧」のケースに使えますが、「暴力」のケースでは使えません。ここでの暴力とは代替手段が無いほど追い詰められた状況です。強盗が家に侵入してきて銃をこちらに向けて指が動くまで後数秒・・・といったケースはそこからどうすることも出来ないためフォーラムシアターには適していません。どうしてもそういったケースを扱いたい場合、その状況が起きる前の時間に巻き戻した時点からアンチ・モデルを生成する必要があります。
