+++
title="インプロの知恵で加速するDDP"
slug="ddp_with_impro"
date="2023-12-17"
author=""
cover=""
tags=["ORSC", "coach"]
keywords=["agile coach","system coach", "ICF"]
description="筆者はORSCCとインプロファシリテーターの二足のわらじを履いています。その観点からちょっと踏み込んだ内容を書いてみようと思いました。"
showFullContent=false
draft=true
+++

//状況：DDPは一番使われていないワーク。実際に難しい
//複雑化：演じること、ゴーストを場に出していくことの２つのエッジが混ざっているからエッジが複数あるように見える。どうやって関係性の変化のエッジに気づけるのか？
//疑問：インプロの知恵はDDPに役に立つのか？
//答え:１７のテクニックで演じることのエッジの捉え方に彩りをを捉えていく
:sectnums:

筆者はORSCCとインプロファシリテーターの二足のわらじを履いています。
その観点からちょっと踏み込んだ内容を書いてみようと思いました。

== 前提知識

* ORSCワークのディープデモクラシープロセス(以下DDP)に関する応用コースレベルの実践知識


=== インプロとは？
[quote, IMPRO ACADEMY, インプロとは？]
インプロとは即興演劇のことです。普通の演劇には台本がありますが、インプロには台本がありません。また、あらすじも決まっていません。本当に先が分からない中で、プレイヤーたちはお互いを受け入れあいインスパイアしあいながらストーリーを生み出していきます。

参照: https://improacademy.jp/impro/

演劇は関係性の芸術と言われており、舞台上でイマココに経ち続け関係性を変化させながら、パートナーシップと自然体であること、その上さらにリスクをとってドラマを作っていきます。
ドラマとはリスクをとって関係性にチャレンジした時に置きます。

== DDPにおけるエッジ行動を観測する難しさ
DDPでエッジ

== エッジ行動をインプロの観点から観測していく。


== ストーリーを止める17のテクニック
include::content/posts/2023/methods_to_kill_stories.adoc[tag=main-table]

== ストーリーを止めるとは？
