+++
title="インプロの知恵でディープデモクラシープロセスをサポートする"
slug="ddp_with_impro"
date="2023-12-19"
author=""
cover=""
tags=["ORSC", "coach", "impro"]
keywords=["system coach", "インプロ", "ディープデモクラシープロセス", "DDP"]
description="システムコーチング Advent Calendar 2023に登録したので、ORSCに関する内容を書きます。筆者はORSCCとインプロファシリテーターの二足のわらじを履いています。その観点からちょっとディープデモクラシープロセス（以下DDP）に関して、考えている内容を書いてみます。"
showFullContent=false
draft=false
+++

:sectnums:

https://adventar.org/calendars/8711[システムコーチング Advent Calendar 2023]に登録したので、ORSCに関する内容を書きます。

筆者はORSCCとインプロファシリテーターの二足のわらじを履いています。
その観点からちょっとディープデモクラシープロセス（以下DDP）に関して、考えている内容を書いてみます。

== 前提知識
. ORSCワークのDDPに関する応用コースレベルの実践知識

前提知識は以上のみとします。

== インプロとは？
[quote, IMPRO ACADEMY, インプロとは？]
インプロとは即興演劇のことです。普通の演劇には台本がありますが、インプロには台本がありません。また、あらすじも決まっていません。本当に先が分からない中で、プレイヤーたちはお互いを受け入れあいインスパイアしあいながらストーリーを生み出していきます。

参照: https://improacademy.jp/impro/

演劇は関係性の芸術と言われており、ORSCを学んだ後に即興演劇の知見を得ると、得心がいくものが多く非常に興味深いものです。

この記事でのインプロを定義しておきます。まず第一に **impro** と **improv** の違いがあります。それぞれ **improvisation** の省略ではあるのですが、アメリカ英語だと impro**+++<u>v</u>+++** が通常の省略になります。それに対して impro はイギリス英語であり、キース・ジョンストンのインプロを指します。また、即興で演じることは決してインプロの専売特許ではなく、ORSCトレーニングの中で行われるロールプレイ的なものも即興演劇的とも言えます。

それらと違い「自発性・利他性・挑戦性」を発揮しながらイマココに経ち続けることを行っているキース・ジョンストンの開発した impro をここでの"インプロ"とします。 +
それ以外の即興性を持って演じることを即興演劇とします。

== DDP中のエッジ行動を捉える難しさ
DDPの話に戻りましょう。DDPはクライアントに対して実施されている回数が少ないとの意味で、世界的に一番人気がないORSCワークとファカルティの方から教えてもらった事があります。それ故に旧来の何も無いところから始まるDDPではなく、今の５つの声バージョンが生まれたと聞いています。

私はさらにそこに加えて、演じることのエッジがあるのではないかと考えています。 +
演じること、つまり他の声・ゴーストそのものになって自己表現することに、クライアントシステムを構成する個々の人が大なり小なりエッジを感じるのではないかと考えています。もちろん学生時代や社会人になってからも演劇に関わっている人もいますので、演じることのエッジがものすごく低い人もいるとは思います。

さらに場に新しい声・ゴーストが出てくることその事自体にも当然エッジがあります。

そしてそれらのエッジはDDPの場では混ざりに混ざってしまっているのではないでしょうか？

== 演じることのエッジを教育でサポートする
まず最初に私がインプロを学び始めた頃に頂いた言葉を置いておきます。
[quote]
想像力の責任をとらない

インプロで教えて頂いた言葉で好きな言葉の上位に入ります。インプロの自発性に関わる言葉です。人は本来アイディアが無限に湧いている状態にあります。そして社会生活の中でそれらを全て出してしまわないように頭の中にいる検閲官が、アイディアが口から出ていかないように止めています。

DDP中にゴーストの声を出そうとしているクライアントシステムの一人も同じように、ゴーストの言葉そのものに行き着いているのですが、その言葉を口から出せない時があると思います。安心安全であり、評価判断の場ではないことを繰り返すことが何より大事です。それに加えて必要そうであれば、私は想像力の責任を取ろうとしているように見えること、ここでは想像力の責任を取らなくても良いことを教育し伝えるようにしています。

== DDP中のエッジ行動をインプロの観点から捉える
DDPの中で新たなゴーストが現れたり、誰も考えたことが無かったような言葉が現れる時、システム内の関係性の新たな一面が見えたり、関係性の捉え方に関する新たな情報が出てきたりします。そういった時にエッジ行動はできますよね。

エッジ行動をインプロの世界ではどう捉えているかというと興味深い知恵があるので紹介しておきます。 +
以下はインプロの知恵の「ストーリーを止める１７のテクニック」です。

[NOTE]
====
ストーリーを止める17のテクニック = エッジ行動のパターン
====

テクニックと書いてますが、これは若干キース・ジョンストンの皮肉的な言い方なので注意して下さい。
また懲罰的に使うものではなく、振り返りや、その場を変えていくために修復的に使われている点にも注意です。ストーリを止めるとはつまり関係性を停滞させることになります。関係性を前に進めて新たな一面を見ることは勇気がいることなので、ついつい演者はストーリーを止める誘惑に負けてしまうこともあります。

以下に整理して置いておきます。
例の内容はインプロアカデミーから頂きました。

include::content/posts/2023/methods_to_kill_stories.adoc[tag=main-table]

如何でしょうか？字面だけでは捉えきれないものもあるかもしれません。
興味を持ってもっと深く知りたい人は、インプロを通じて体得するようなトレーニングに参加することをお勧めします。

== ストーリーを止めるテクニックを観測した後に

エッジ行動は自然現象で、矯正されるものではないし、またエッジを超えて２次に行くことはクライアントシステムの選択であることを前提として、エッジを超えるお誘いをすることもコーチがそこに立っている一つの理由だと思います。

例えば、あるゴーストが他のゴーストと同じような行動・発言を取っている時、それは Joining かもしれません。
「あなたは◯◯（Joining相手の声・ゴースト）と何が違いますか？」
と誘ってみても良いかもしれません。

まだ場に出ていないゴーストの話が出てきたら、 Gossiping かもしれませんし、他の声・ゴーストが出てくるサインかも知れません。

Cancelling を観測したら「受け入れたとしたら、何がはじまりそうですか？」とお誘いしてみても良いかもしれませんね。

== 最後に
私はDDPが大好きですが、同時にクライアントに対して実施しる難しさも感じています。今日紹介させて頂いたインプロの知恵がそこの難しさを少し軽減できれば良いなと願っていると同時に、もしかしたらDDPの本来の効果効能から離れてしまうかもしれないという恐れも持っています。そういった恐れを持ちながらも世の中に広めてみたくてこの文章を書きました。

ご意見ご感想などありましたら、どこかでお声をかけて下さい。

