+++
title="小さな会社でスクラムマスターを雇うときの期待"
slug="expectation_for_scrum_master"
date="2023-12-21"
author=""
cover=""
tags=["Scrum Master"]
keywords=[]
description=""
showFullContent=false
draft=true
+++

この前あるまだ少人数のスタートアップ企業の人から、小さな会社でスクラムマスターを雇った方が良いのか？みたいな相談があったのでそこで考えた所感を書いてみます。

== 少人数の会社に入るスクラムマスターに最低限期待する事
少人数のスタートアップであれば、スクラムマスターとして１チームのスクラムを見るだけでは仕事はまわりませんよね。

まずスクラムマスターに期待する第一のことはスクラムの導入・運営を経験していることです。
ふりかえりがきちんとできるとか、スプリントレビューをファシリテートしたことがあるとかは、その一要素に過ぎません。

勿論、スクラムの導入・運営が難しいチームや会社もあると思います。
とはいえ、困難を乗り越えてチームにスクラムを導入し、運営した経験は必要になります。

ここでの導入も運営もその場の主体になっているかは、時には大事ではない場合もあります。
ただし、意図を持って、その場に関わっていた必要はあると考えています。

これは、ソフトウェアエンジニアであれば、何らかのサービスやアプリを作り始めから、運営まで関わった経験と似ているかもしれません。こういった経験なしで、小さなスタートアップに入るのは、まぁまぁ危ないかなと思います。たまに小さなスタートアップでもジュニア採用している場合もありますが、大抵シニア採用ですよね。スクラムマスターも同じだと思います。

== シニアなスクラムマスターに期待する事ってスクラムだけじゃないよね？
シニアなスクラムマスターの話に行く前に、シニアなソフトウェアエンジニアの話でいうと。仮に

--

さて、普通のシニアを超えた時にはマスターレベルになっていきます。
マスターレベルのアンドルーのエンジニア、何ができるでしょうか？
高速にアンドロイドアプリの開発ができるまず、これが一つあります。
次にandroid以外のところにも手を入れていけるというのは、私が考えていることです。
バックエンドの実装をフロントエンドの実装ウェブフロントエンドの実装。
さらにはios、android両方使ったプロダクトの設計。
もう少し抗議にモバイルエンジニアと言ってもいいでしょう。

ではスクラマスターどうなるか？
スクラムが実装できることが初級のシニアレベルだとしたら、マスターレベルでできることというのは、スクラムの要素。溶血フレームワークの構成要素をしっかりと理解した上で、今その会社に求められている形は何かを模索する能力が必要になると思っています。
そしてそれはすでにスクラムではありません。スクラムは全体性という言葉を好んでますよね。私嫌いですけど。
そしてスクラムである必要性はありません。

アジャイルである必要性はあると思います。
スクラムはとりあえずスタートするためのええ。スタートアップキットとしては、僕は最強の部類に入ると思っています。
同時にフルセットすぎるので小さい小さい会社だとちょっと大きすぎるということもあるかもしれません。
この小さい会社というのは、決して人数だけのことを表しているわけではないことに注意してください。
スクランマスターに求められること。それは臨機応変にアジャイルが開発プロセスを構成することだと私は思っています。

そしてそれが相談できる良いパートナーシップであれば小さいスタートアップでもスクラムマスターを雇う価値はあると思っています。
なので、スクラムができるかどうかというのは、まず最低要件として。
次にどのように今の会社に何を適用して、それをどのようにインストレーション立場を取っていくかということが見えている人というのが、スタートアップに向いているクラブマスターだと私は思っています。

これはスタートアップの初めてエンジニアになる人たちにも同じようなことが言えます。

