+++
title="ストーリーを止める17のテクニック"
slug="methods_to_kill_stories"
date="2023-10-17"
author=""
cover=""
tags=["impro"]
keywords=["impro","インプロ"]
description="インプロアカデミのトレーニング・ワークショップで学んだ キースジョンストンの「ストーリーを止める17のテクニック」が非常に面白かったのでまとめておきます。"
showFullContent=false
draft=false
+++

:sectnums:

== この記事について

https://improacademy.jp/[インプロアカデミー] で行われたimprofootnote:[即興演劇、improvでなくimproで表現する時はキースジョンストンの即興劇を示す。]のトレーニング・ワークショップで学んだ キースジョンストンの「ストーリーを止める17のテクニック」が非常に面白かったのでまとめておきます。

=== ストーリーを止めるとは？
即興演劇は関係性の芸術だとも教わりました、関係性を舞台の上で変化をさせていくのが劇ということになります。関係性が進むことがつまりストーリーを進めることになります。ドラマチックにストーリーを進めていくことで関係性が変化していきます。関係性を変化させていくことには勇気が必要です。そういった時に人は本能的にストーリーを止めてしまいます。

=== ストーリーを止めるテクニックとは？
キースジョンストンがimpro中に出てくる、ドラマを止める演者の振る舞いをリスト化したものです。ただし17のテクニックは完全な分類ではなく、似ているものもあることに注意して下さい。完全な分類が目的ではなく、なぜストーリーがうまく進まないのかそこに気づきやすく、ふりかえりをやりやすくするためのものです。

== 資料

NOTE: 資料の公開はインプロアカデミーから掲載許可を頂いています。

[quote, Keith Johnstone]
大人は何事も起こさない天才である。

インプロの中で、未知や変化や評価を恐れて無意識にやってしまう行動集。
「テクニック」とついているが、これはキースジョンストンの皮肉。

// tag::main-table[]
[%header, cols="1,1,2", stripes=even]
.ストーリーを止める17のテクニック
|====

|名前
|説明
|例

|Blocking
|相手のアイデアを否定する。受け入れない。
|おばあさん「桃を持って帰って来ました」  +
おじいさん「私は桃は嫌いだ！」

|Being negative
|ネガティブになる。
|おじいさんとおばあさんは体調が悪いので、今日は一日家で休むことになりました。

|Wimping
|物事を曖昧にする。具体的に決めない。
|すると川から、大きくて、動いていて、変な匂いがする、何かが流れて来ました。

|Cancelling
|それまでに起こったことを無かったことにする。
|おじいさんとおばあさんはやっぱり桃を川へ返しにくことにしました。

|Joining
|相手と同じ状態になる。
|おじいさんも、おばあさんも山へ芝刈りに行きました。

|Gossiping
|今ここにないことを話す。
|村人A「隣のおばあさんが、川で大きな桃を見つけたらしいよ」 +
村人B「そこから子供が出て来たらしいよ」

|Agreed activities
|相手と一緒に何でもない行動をする。
|山へ柴刈りに行った2人は、一日枝を拾い集めていました。

|Bridging
|既に見えている結末になかなか向かわない。
|まずは桃をどのように切るか、印をつけることにしました。 +
次に、包丁をよく研ぐことにしました。

|Hedging
|今やるべきことを先延ばしにする。
|おばあさん「何という名前にしましょうか」 +
おじいさん「それは明日考えよう」

|Sidetracking
|ストーリーの本筋ではないこと（リスクが小さいこと）をする。 
|おばあさんはきび団子を作るために、きび団子教室に通うことにしました。

|Being original
|独創的で奇抜なアイデアを出す。
|川から巨大なペペロンチーノが流れて来ました。

|Looping
|同じことを繰り返す。（三回ぐらいは別にいい）
|（犬猿雉に続いて）ネズミに出会いました。次に牛に出会いました。そして虎に出会いました。

|Gagging
|くだらないギャグを言ったりやったりする。
|おばあさん「何という名前にしましょうか」 +
おじいさん「すももももももものうち太郎という名前にしましょう」

|Comic exaggeration
|漫画のような胡蝶表現をする。
|大きな桃を見つけたおばあさんは、驚きのあまり月まで飛んでいきました。

|Conflict
|相手とすぐに（小さな）対立する。
|おばあさん「さぁ、桃を切りましょう」 +
おじいさん「いや、この桃は観賞用にしよう」

|Instant trouble
|冒頭でいきなり問題を起こす。
|おばあさんは川に落ちてしまいました。

|Lowering the stakes
|リスクを下げる。
|おじいさん「途中で犬猿雉を仲間にすれば鬼に勝てるよ」

|====
// end::main-table[]

ストーリーを止めるテクニックは、だいたい未知や変化や評価への恐れによって行われている。そのチェックポイントになる。 +
逆に言えば、遊び心や好奇心からストーリーを止めるテクニックを使っているのであれば、それは試してみればいい。

良いインプロはリスキーなもの。

== トレーニング・ワークショップを終えてみて
まずはこのトレーニングを受けることができて本当に幸いだったと思います。
講師の方も結構実験的な試みだったと言われていました。

私自身の変化として、コーチ、ファシリテーターへのメンターとしてのフィードバックの精度が格段に上がりました。場を動かしていく変化を助成していくことは、舞台の上と同じように勇気が必要です。つい、怖気づいてしまうこともあります。メンターとしてはそこをしっかりポイントして上げることが重要になると思っています。
ファシリテーター自身の行動としてストーリを止めるテクニックは顕著に現れますし、また、場の動きとしても現れやすいです。

さらにシステムコーチング®footnote:[システムコーチング®は、CRR Global Japan 合同会社の登録商標です。 http://www.crrglobaljapan.com]を行っている時にも役に立っているのですが、それはまた別の記事で書きたいと思います。




