+++
title="ストーリーを止める17のテクニック"
slug="methods_to_kill_stories"
date="2023-10-17"
author=""
cover=""
tags=["impro"]
keywords=["impro","インプロ"]
description="impro で"
showFullContent=false
draft=false
+++

:sectnums:
:toc:
:toclevels: 3

== ストーリーを止めるテクニックとは？

https://improacademy.jp/[インプロアカデミー] で行われたトレーニングで学んだ impro の

== 内海さんの資料

インプロの中で、未知や変化や評価を恐れて無意識にやってしまう行動集。
「テクニック」とついているが、これはキースジョンストンの皮肉。

> 大人は何事も起こさない天才である。
Keith Johnstone

※17のテクニックは完全な分類ではなく、似ているものもある。


Blocking::
相手のアイデアを否定する。受け入れない。  ::::
おばあさん「桃を持って帰って来ました」  +
おじいさん「私は桃は嫌いだ！」

Being negative::
ネガティブになる。::::
おじいさんとおばあさんは体調が悪いので、今日は一日家で休むことになりました。

Wimping::
物事を曖昧にする。具体的に決めない。::::
すると川から、大きくて、動いていて、変な匂いがする、何かが流れて来ました。

Cancelling::
それまでに起こったことを無かったことにする。::::
おじいさんとおばあさんはやっぱり桃を川へ返しにくことにしました。

Joining::
相手と同じ状態になる。::::
おじいさんも、おばあさんも山へ芝刈りに行きました。

Gossiping::
今ここにないことを話す。::::
村人A「隣のおばあさんが、川で大きな桃を見つけたらしいよ」 +
村人B「そこから子供が出て来たらしいよ」

Agreed activities::
相手と一緒に何でもない行動をする。::::
山へ柴刈りに行った2人は、一日枝を拾い集めていました。

Bridging::
既に見えている結末になかなか向かわない。::::
まずは桃をどのように切るか、印をつけることにしました。 +
次に、包丁をよく研ぐことにしました。

Hedging::
今やるべきことを先延ばしにする。::::
おばあさん「何という名前にしましょうか」 +
おじいさん「それは明日考えよう」

Sidetracking::
ストーリーの本筋ではないこと（リスクが小さいこと）をする。 ::::
おばあさんはきび団子を作るために、きび団子教室に通うことにしました。

Being original::
独創的で奇抜なアイデアを出す。 ::::
川から巨大なペペロンチーノが流れて来ました。

Looping::
同じことを繰り返す。（三回ぐらいは別にいい）::::
（犬猿雉に続いて）ネズミに出会いました。次に牛に出会いました。そして虎に出会いました。

Gagging::
くだらないギャグを言ったりやったりする。::::
おばあさん「何という名前にしましょうか」 +
おじいさん「すももももももものうち太郎という名前にしましょう」

Comic exaggeration::
漫画のような胡蝶表現をする。::::
大きな桃を見つけたおばあさんは、驚きのあまり月まで飛んでいきました。

Conflict::
相手とすぐに（小さな）対立する。::::
おばあさん「さぁ、桃を切りましょう」 +
おじいさん「いや、この桃は観賞用にしよう」

Instant trouble::
冒頭でいきなり問題を起こす。::::
おばあさんは川に落ちてしまいました。

Lowering the stakes::
リスクを下げる。::::
おじいさん「途中で犬猿雉を仲間にすれば鬼に勝てるよ」


---


ストーリーを止めるテクニックは、だいたい未知や変化や評価への恐れによって行われている。そのチェックポイントになる。逆に言えば、遊び心や好奇心からストーリーを止めるテクニックを使っているのであれば、それは試してみればいい。

いいインプロはリスキーなもの。